DROP DATABASE IF EXISTS TODODB;

CREATE DATABASE TODODB;

use TODODB;

CREATE TABLE USER (
    USER_ID int NOT NULL AUTO_INCREMENT,
    USER_EMAIL varchar(255) UNIQUE NOT NULL,
    USER_PASS varchar(60) NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE TODO (
    TODO_ID int NOT NULL AUTO_INCREMENT,
    USER_ID int NOT NULL,
    TODO_TASK varchar(255) NOT NULL,
    TODO_PRIORITY int NOT NULL,
    TODO_COMPLETE int NOT NULL DEFAULT 0,
    TODO_COUNT int,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    PRIMARY KEY (TODO_ID)
);